server:
  port: 81

spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  cloud:
    nacos:
      # 服务注册中心
      discovery:
        server-addr: 192.168.10.100:8848
    # 服务网关
    gateway:
      discovery:
        locator:
          enabled: true    #开启动态路由
          lower-case-service-id: true
      routes:
        #--------------- service-9001-hosp 反向代理-------------------
        - id: service-oms
          uri: lb://service-oms
          predicates:
            - Path=/oms/**
        #--------------- service-9002-auth 反向代理-------------------
        - id: service-auth
          uri: lb://service-auth
          predicates:
            - Path=/admin/*/**
        #--------------- service-9003-cmn 反向代理-------------------

  # redis && redis pool
  # mongodb
  # rabbitmq

# 日志
logging:
  level:
    root: info
  charset:
    file: UTF-8
  file:
    name: ./logs/service-gateway-80.log
