/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c3c5d8",
        "primary-container": "#2f6bff",
        "tertiary-fixed": "#ffdbcd",
        "on-tertiary-fixed-variant": "#7c2d00",
        "on-primary-fixed-variant": "#003cac",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d9d9e5",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#434655",
        "on-secondary-fixed-variant": "#005049",
        "inverse-on-surface": "#f0f0fc",
        "on-tertiary-container": "#ffffff",
        "primary-fixed-dim": "#b5c4ff",
        "tertiary-container": "#cb4f00",
        tertiary: "#a33e00",
        "on-tertiary-fixed": "#360f00",
        "surface-bright": "#faf8ff",
        "on-error": "#ffffff",
        "surface-tint": "#0051e0",
        "on-secondary": "#ffffff",
        "surface-container": "#ededf9",
        "surface-container-high": "#e7e7f4",
        "secondary-container": "#6af5e5",
        "primary-fixed": "#dbe1ff",
        "surface-variant": "#e1e1ee",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#b5c4ff",
        background: "#faf8ff",
        "secondary-fixed": "#6df8e7",
        "surface-container-highest": "#e1e1ee",
        "on-secondary-container": "#006f66",
        outline: "#737687",
        surface: "#faf8ff",
        secondary: "#006a61",
        "on-surface": "#191b24",
        "tertiary-fixed-dim": "#ffb596",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#00174d",
        "surface-container-low": "#f3f3ff",
        error: "#ba1a1a",
        "on-primary-container": "#000318",
        "secondary-fixed-dim": "#4bdbcb",
        "on-secondary-fixed": "#00201d",
        "on-background": "#191b24",
        primary: "#0051df",
        "inverse-surface": "#2e3039",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        "section-padding": "20px", "touch-target-min": "48px",
        "container-margin": "16px", "inline-gap": "8px",
        "tab-bar-height": "83px", "stack-gap": "12px", "nav-bar-height": "47px",
      },
      fontFamily: {
        "data-display": ["Inter"], caption: ["Inter"], "section-title": ["Inter"],
        "body-bold": ["Inter"], "nav-title": ["Inter"], "body-main": ["Inter"],
        sans: ["Inter", "PingFang SC", "sans-serif"],
      },
      fontSize: {
        "data-display": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        caption: ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "section-title": ["17px", { lineHeight: "24px", fontWeight: "600" }],
        "body-bold": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "nav-title": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-main": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
