
server.port=9222

# \u5FAE\u670D\u52A1\u540D\u79F0
spring.application.name=service-auth

# \u73AF\u5883\u6D4B\u8BD5 dev\u5F00\u53D1 test\u6D4B\u8BD5 prod\u751F\u4EA7
spring.profiles.active=dev

# \u6570\u636E\u6E90
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tms_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=123456

# MyBatisPlus\u65E5\u5FD7
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# json\u65F6\u95F4\u683C\u5F0F
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai

# \u7AEF\u70B9\u76D1\u6D4B
management.endpoints.web.exposure.include=*

# \u65E5\u5FD7
logging.level.root=info
logging.level.com.geek.yygh.controller=debug
logging.charset.file=UTF-8
logging.file.name=./logs/service-9222-auth.log

# nacos\u5730\u5740
spring.cloud.nacos.discovery.server-addr=192.168.10.100:8848
# openfeign\u65E5\u5FD7\u589E\u5F3A

# redis
spring.data.redis.database=2
spring.data.redis.host=192.168.10.100
spring.data.redis.port=6379
spring.data.redis.password=lyynb666
spring.data.redis.timeout=180000
# redis lettuce pool
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=100
spring.data.redis.lettuce.pool.max-idle=30
spring.data.redis.lettuce.pool.min-idle=10
spring.data.redis.lettuce.pool.max-wait=-1

# mongodb\u5730\u5740

# rabbitmq

